#!/usr/bin/env php
<?php

namespace Fuz;

if (file_exists($autoload = __DIR__.'/../../../autoload.php')) {
    require_once $autoload;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

$app = new RandomApplication();
$app->run();
